### ISSUE TITLE
isRemoval prop

### ISSUE THREAD

**Issue by cyouh95** [davidlarcher/jammming#3]
[Here](https://github.com/davidlarcher/jammming/blob/master/src/Components/Track/Track.js#L26), instead of displaying both `+` and `-` for all the tracks, you could utilize the `isRemoval` prop passed to the **Track** component to determine which button to use.

For example, if `this.props.isRemoval` is false (ie. for the tracks in [searchResults](https://github.com/davidlarcher/jammming/blob/master/src/Components/SearchResults/SearchResults.js#L10)), then you'd want the `+` button to be able to add the track. And if `this.props.isRemoval` is true (ie. tracks in [playlist](https://github.com/davidlarcher/jammming/blob/master/src/Components/Playlist/Playlist.js#L19)), you'd want the `-` button.

One way you could implement this is by using the [ternary operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator).

**Comment by davidlarcher** [comment]
thank you, this is what I did :
render() {
        const button = this.props.isRemoval ? (
            <a className="Track-action" onClick={this.removeTrack}> - </a>
        ) : (
            <a className="Track-action" onClick={this.addTrack}> + </a>
        )
        return (
            <div className="Track">
                <div className="Track-information">
                    <h3>{this.props.track.name}</h3>
                    <p>{this.props.track.artist} | {this.props.track.album}</p>
                </div>
                {button}
            </div>

        );
    };
