### ISSUE TITLE
Remove hardcoded tracks

### ISSUE THREAD

**Issue by cyouh95** [davidlarcher/jammming#4]
The hardcoded [searchResults](https://github.com/davidlarcher/jammming/blob/master/src/Components/App/App.js#L12-L26) and [playlistTracks](https://github.com/davidlarcher/jammming/blob/master/src/Components/App/App.js#L29-L48) are great to have to help you during the development process, but don't forget to remove them for your final product.

**Comment by davidlarcher** [comment]
done
